### ISSUE TITLE
Other apps files are deleted at Images startup

### ISSUE THREAD

**Issue by mmnosek** [StarcounterPrefabs/Images#56]
At a test environment (one server) I have two databases running exactly the same set of apps. Images is obviously one of them. We've realised, that sometimes image and other files are missing, but without any specific pattern. I found out that at every application startup we execute this method:
https://github.com/StarcounterPrefabs/Images/blob/master/src/Images/Helpers/IllustrationHelper.cs#L82

So basically we delete all files that don't exist in starting app's database. What is the reason to delete this files automatically at startup? I think that this behaviour is very unpredictable for user/administrators. I know, that I can set up different upload folders for each app in settings, but only after startup, so it's to late. Most of the users just don't change default settings at all.

I propose to remove this function. WDYT?

cc @warpech @miyconst @aloscha

**Comment by warpech** [comment]
I totally agree that the app should not make a decision to delete all files in the directory. Please remove this feature and the helper method.

In future, we might add an admin page to manage files in the media files directory. But that would be a more complex feature, that would allow you to check what files are used.

Please test what happens when you try to upload a file with a name that already exists in the directory.

**Comment by warpech** [comment]
An afterthought: Just keep the helper method, but don't call it at the application startup. Bind it to a button on the Settings page instead.

**Comment by warpech** [comment]
PR #58 merged to `develop`. Thanks!
